services: 
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USER: estevao
      DB_PASS: alves2403
      DB_NAME: db_nike
      DB_HOST: db
      JWT_SECRET: fsdf64s6df11s6dfs684f8sd
    volumes:
      - ./:/app-backend
    container_name: backend_container
    restart: always
    depends_on:
      - db

  db: 
    image: postgres:15
    ports: 
      - "5434:5432"
    environment:
      POSTGRES_USER: estevao
      POSTGRES_PASSWORD: alves2403
      POSTGRES_DB: db_nike
    container_name: db_nike_container
    restart: always
